version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    command: npm run start:dev:api-gateway
    environment:
      RABBITMQ_URL: amqp://localhost:5672
    depends_on:
      - rabbitmq
    ports:
      - "4000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  questions:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: questions
    command: npm run start:dev:questions
    environment:
      RABBITMQ_URL: amqp://localhost:5672
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  answers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: answers
    command: npm run start:dev:answers
    environment:
      RABBITMQ_URL: amqp://localhost:5672
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
